# Generated by Django 4.2.7 on 2024-11-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_brand_remove_product_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, default="mes", max_length=255, null=True
            ),
        ),
    ]
