# Generated by Django 4.2.7 on 2024-12-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_category_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="name",
        ),
    ]
