# Generated by Django 4.2.7 on 2024-12-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_category_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/category/"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="uploads/products/"),
        ),
    ]
